### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by jarythee** [dyarleniber/AD5933-arduino-bioimpedance#1]
Good day sir, I want to know the result of the bioimpedance. If it accurately read the bioimpedance of a person. And if possible, can I ask the schematic diagram of this project. Thank you @dyarleniber :)

**Comment by dyarleniber** [comment]
Hi Jaryeth, yes sure :)
I've sent you an email with more details.

**Comment by jarythee** [comment]
Thank you Mr. Dyarlen Iber

**Comment by dmazzella** [comment]
> Hi Jaryeth, yes sure :)
> I've sent you an email with more details.

Hi @dyarleniber is possible to have more details?

Thanks,
D.
