### ISSUE TITLE
Bachelor Thesis Link is broken

### ISSUE THREAD

**Issue by andy-96** [dyarleniber/AD5933-arduino-bioimpedance#2]
Hi @dyarleniber ,

I'm currently looking into measuring bioimpedance using an Arduino. I would love to have a look into your Bachelor thesis however your link seems to be broken. Could you upload it again?

Cheers,

Andy

**Comment by dyarleniber** [comment]
Hi Andy,

It's not broken. This is the link: https://github.com/dyarleniber/AD5933-arduino-bioimpedance/raw/master/final-paper-dyarleniber.pdf

This is a PDF file, so you need to download and open it on your computer. The link above should work. (It was written in Portuguese, I  don't have a English version)

**Comment by andy-96** [comment]
Oh yes, now it is working! Maybe it was down for a minute. Thanks a lot!
